apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reloader
resources:
  - ../../base
helmCharts:
  - name: reloader
    releaseName: reloader
    version: 1.1.0
    repo: https://stakater.github.io/stakater-charts
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values.yaml
