apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
        - git:
            files:
              - path: cluster-addons/**/overlays/eks-dev-01/config.json
            repoURL: https://github.com/diegoluisi/gitops-multicluster.git
            requeueAfterSeconds: 20
            revision: ""
            template:
              metadata: {}
              spec:
                destination: {}
                project: ""
                source:
                  repoURL: ""
        - list:
            elements:
            - cluster: engineering-dev
              url: https://kubernetes.default.svc
              values:
                project: dev
            - cluster: engineering-prod
              url: https://1.2.3.4
              values:
                project: prod
  template:
    metadata:
      name: '{{.userGivenName}}-{{.cluster}}'
    spec:
      project: 'default'
      source:
        repoURL: https://github.com/diegoluisi/gitops-multicluster.git
        targetRevision: "{{ .srcTargetRevision }}"
        path: "{{ .srcPath }}"
      destination:
        server: "{{.url}}'"
        namespace: '{{ .destNamespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true               