apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    # Directory generator for detecting each addon inside cluster-addons/
    - git:
        repoURL: https://github.com/diegoluisi/gitops-multicluster.git  # Your GitOps repo
        revision: ""  # Branch or tag to track
        files:
          - path: cluster-addons/**/config.json  # Look for all directories under cluster-addons
        requeueAfterSeconds: 20  # Requeue every 20 seconds
        template:
          metadata: {}
          spec:
            destination: {}
            project: ""
            source:
              repoURL: ""          
  template:
    metadata:
      name: "{{.path.basename}}-{{.appName}}"  # App name will be addon name + cluster
    spec:
      project: default
      source:
        path: '{{.path.path}}'
        repoURL: "{{ .srcRepoURL }}"
        targetRevision: "{{ .srcTargetRevision }}"
      destination:
        namespace: '{{.destNamespace}}'
        server: '{{ .destServer }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace='{{default "true" .CreateNamespace }}'
status: {}