apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]  # You can switch to "missingkey=default" to avoid hard errors.
  generators:
    - git:
        repoURL: https://github.com/diegoluisi/gitops-multicluster.git  # Your GitOps repo
        revision: HEAD  # Ensure you are tracking a valid branch or tag
        files:
          - path: cluster-addons/**/config.json  # Look for all directories under cluster-addons
        requeueAfterSeconds: 20  # Requeue every 20 seconds
  template:
    metadata:
      name: "{{ .path.basename }}-{{ .path.appName | default 'cluster' }}"  # App name will be addon name + cluster
    spec:
      project: default
      source:
        repoURL: "{{ .repoURL | default 'https://github.com/diegoluisi/gitops-multicluster.git' }}"  # Fallback to default if missing
        targetRevision: "{{ .srcTargetRevision | default 'HEAD' }}"  # Default to HEAD if not provided
        path: "{{ .path.path }}"  # The path to the addon
      destination:
        namespace: '{{ .destNamespace | default "default" }}'  # Default namespace
        server: '{{ .destServer }}'  # Default API server
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace='{{ .CreateNamespace | default "true" }}'
