apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
        - git:
            repoURL: https://github.com/diegoluisi/gitops-multicluster.git
            revision: HEAD
            files:
              - path: cluster-addons/**/config.yaml
            requeueAfterSeconds: 20
            # directories:
            # - path: cluster-addons/*
        - clusters:
            selector:
              matchLabels:
                cluster-addons: "true"
  template:
    metadata:
      name: '{{.path.basename}}-{{.userGivenName}}'
    spec:
      project: 'default'
      source:
        repoURL: https://github.com/diegoluisi/gitops-multicluster.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: '{{.server}}'
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true               