apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]  # You can switch to "missingkey=default" to avoid hard errors.
  generators:
    - git:
        files:
          - path: cluster-addons/**/config.json  # Look for all directories under cluster-addons
        repoURL: https://github.com/diegoluisi/gitops-multicluster.git  # Your GitOps repo
        requeueAfterSeconds: 20  # Requeue every 20 seconds
        revision: "" # Ensure you are tracking a valid branch or tag
        template:
          metadata: {}
          spec:
            destination: {}
            project: ""
            source:
              repoURL: ""        
  template:
    metadata:
      name: "{{ .appName  }}-{{ .path.basename }}"  # App name will be addon name + cluster
    spec:
      project: default
      source:
        repoURL: '{{ default "https://github.com/diegoluisi/gitops-multicluster.git" .srcRepoURL }}'  # Fallback to default if missing
        targetRevision: "{{ .srcTargetRevision }}"  # Default to HEAD if not provided
        path: "{{ .path.path }}"  # The path to the addon
      destination:
        namespace: '{{ .destNamespace }}'  # Default namespace
        server: '{{ .destServer }}'  # Default API server
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace='{{ default true .CreateNamespace }}'
