apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
        - git:
            files:
              - path: cluster-addons/**/overlays/**/config.json
            repoURL: https://github.com/diegoluisi/gitops-multicluster.git
            requeueAfterSeconds: 20
            revision: ""
            template:
              metadata: {}
              spec:
                destination: {}
                project: ""
                source:
                  repoURL: ""
        - clusters:
            selector:
              matchLabels:
                cluster-addons: "true"
  template:
    metadata:
      name: '{{.userGivenName}}-{{.path.basename}}'
    spec:
      project: 'default'
      source:
        repoURL: https://github.com/diegoluisi/gitops-multicluster.git
        targetRevision: "{{ srcTargetRevision }}"
        path: "{{ srcPath }}"
      destination:
        server: "{{.server}}"
        namespace: '{{ destNamespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true               