apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - union:
              mergeKeys:
                - cluster
              generators:
                - git:
                    repoURL: https://github.com/diegoluisi/gitops-multicluster.git
                    revision: HEAD
                    files:
                    - path: cluster-addons/**/overlays/**/config.json
                - list:
                    elements:
                    - cluster: engineering-dev
                      url: https://kubernetes.default.svc
                      values:
                        project: dev
                    - cluster: engineering-prod
                      url: https://1.2.3.4
                      values:
                        project: prd
        template:
          metadata:
            name: '{{.path.basename}}-{{.cluster}}'
          spec:
            project: '{{.values.project}}'
            source:
              repoURL: https://github.com/diegoluisi/gitops-multicluster.git
              targetRevision: HEAD
              path: '{{.path.path}}'
            destination:
              server: '{{.url}}'
              namespace: '{{.path.basename}}'
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              retry:
                limit: 10
                backoff:
                  duration: 1m
                  factor: 2
                  maxDuration: 16m
              syncOptions:
                - CreateNamespace=true
                - ApplyOutOfSyncOnly=true
                - ServerSideApply=true               