apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/diegoluisi/gitops-multicluster.git
      revision: HEAD
      files:
      - path: "cluster-config/**/config.json"
  template:
    metadata:
      name: 'guestbook-{{.cluster.name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/diegoluisi/gitops-multicluster.git
        targetRevision: HEAD
        path: "apps/guestbook"
        # helm:
        #   valueFiles:
        #     - ../values/{{ environment }}.yaml        
      destination:
        server: '{{.cluster.address}}'
        namespace: 'guestbook-{{.cluster.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true        